window:
  opacity: 0.98
  decorations: none
font:
  size: 11
  normal:
    family: MesloLGS NF
  offset:
    y: 25
  glyph_offset:
    x: 0
    y: 10
colors:
  primary:
    background: '#111921'
    foreground: '#ebe6d7'
  normal:
    black: '#000000'
    red: '#ff4c41'
    green: '#c4d264'
    yellow: '#eccd58'
    blue: '#40b2e0'
    magenta: '#f5878a'
    cyan: '#a3e9d4'
    white: '#fffefe'
  bright:
    black: '#414141'
    red: '#ff7c77'
    green: '#edfb95'
    yellow: '#fff68b'
    blue: '#77dcff'
    magenta: '#ffb4b8'
    cyan: '#d0fefd'
    white: '#fffefe'
