AllCops:
  NewCops: enable
  Exclude:
    - "config/**/*"
    - "Rakefile.rb"

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
