require("config.ale")
require("config.gitsigns")
require("config.lualine")
require("config.nvim-cmp")
require("config.nvim-lspconfig")
require("config.nvim-tree")
require("config.set")
-- require("config.telescope")
